# Generated by Django 4.2.7 on 2024-02-22 08:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mortality", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortality",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, null=True
            ),
        ),
    ]
