# Generated by Django 4.2.14 on 2024-09-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo_area", "0002_alter_geoarea_geom"),
        ("mortality", "0005_mortality_comment_mortality_data_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortality",
            name="areas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Associated Administrative and Natural Areas",
                related_name="%(class)s_areas",
                to="geo_area.geoarea",
                verbose_name="Associated Administrative and Natural Areas",
            ),
        ),
    ]
