# Generated by Django 4.2.16 on 2024-11-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cables", "0009_alter_diagnosis_sgmt_landscape_integr_risk_and_more"),
        ("mortality", "0006_mortality_areas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mortality",
            name="infrstr",
            field=models.ForeignKey(
                blank=True,
                help_text="Infrastructure related to mortality case",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mortality",
                to="cables.infrastructure",
                verbose_name="Infrastructure related to mortality case",
            ),
        ),
    ]
