# Generated by Django 4.2.27 on 2026-01-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mortality", "0007_alter_mortality_infrstr"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mortality",
            old_name="nb_death",
            new_name="count",
        ),
        migrations.AlterField(
            model_name="mortality",
            name="count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number found dead"
            ),
        ),
    ]
