# Generated by Django 4.2.7 on 2023-12-06 11:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # ("sinp_nomenclatures", "0003_rename_item_nomenclature"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("media", "0002_alter_media_storage"),
        ("cables", "0004_alter_infrastructure_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineOperation",
            fields=[
                (
                    "operation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cables.operation",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cables.operation",),
        ),
        migrations.CreateModel(
            name="PointOperation",
            fields=[
                (
                    "operation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cables.operation",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cables.operation",),
        ),
        migrations.RemoveField(
            model_name="operation",
            name="eqmt_type",
        ),
        migrations.AlterField(
            model_name="action",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                help_text="Media attached with this diagnosis",
                related_name="diagnosis_media",
                related_query_name="actions",
                to="media.media",
                verbose_name="Media attached with this diagnosis",
            ),
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Number of equipments"
                    ),
                ),
                (
                    "reference",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Equipment model reference",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Comments"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Type of equipment",
                        limit_choices_to={"type__mnemonic": "equipment_type"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_pole_eqmt_type",
                        to="sinp_nomenclatures.nomenclature",
                        verbose_name="Type of equipment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="operation",
            name="equipments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Equipements",
                related_name="equipment",
                related_query_name="operations",
                to="cables.equipment",
                verbose_name="Equipments",
            ),
        ),
    ]
