# Generated by Django 4.2.7 on 2023-12-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cables", "0005_lineoperation_pointoperation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="change_advice",
            field=models.BooleanField(
                default=False, verbose_name="Change arming"
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="technical_proposal",
            field=models.TextField(
                blank=True, null=True, verbose_name="Technical proposal"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="attraction_advice",
            field=models.BooleanField(
                default=False, verbose_name="Providing incentives"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="dissuasion_advice",
            field=models.BooleanField(
                default=False, verbose_name="Discourage"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="isolation_advice",
            field=models.BooleanField(
                default=False, verbose_name="To be insulated"
            ),
        ),
    ]
