# Generated by Django 4.2.7 on 2023-12-06 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_content", "0003_news_private"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name_plural": "News"},
        ),
        migrations.AlterModelOptions(
            name="partners",
            options={"verbose_name_plural": "Partners"},
        ),
    ]
