# Generated by Django 4.2.7 on 2023-11-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map_layers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselayers",
            name="layer_type",
            field=models.CharField(
                choices=[("base", "Base"), ("overlay", "Overlay")],
                default="overlay",
                max_length=50,
                verbose_name="Type de couche (leaflet layer_type)",
            ),
        ),
    ]
