# Generated by Django 4.2.7 on 2023-12-13 11:50

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sinp_nomenclatures", "0003_rename_item_nomenclature"),
        ("geo_area", "0002_alter_geoarea_geom"),
        ("sensitive_area", "0001_initial"),
        ("media", "0002_alter_media_storage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Number of equipments"
                    ),
                ),
                (
                    "reference",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Equipment model reference",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Comments"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Type of equipment",
                        limit_choices_to={"type__mnemonic": "equipment_type"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_pole_eqmt_type",
                        to="sinp_nomenclatures.nomenclature",
                        verbose_name="Type of equipment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Infrastructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Identifiant unique",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "geo_area",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Associated Administrative and Natural Areas",
                        related_name="%(class)s_geo_area",
                        to="geo_area.geoarea",
                        verbose_name="Associated Administrative and Natural Areas",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Infrastructure owner",
                        limit_choices_to={"type__mnemonic": "owner"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owner",
                        to="sinp_nomenclatures.nomenclature",
                        verbose_name="Infrastructure owner",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "sensitive_area",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Associated Sensitivity Areas",
                        related_name="%(class)s_sensitive_area",
                        to="sensitive_area.sensitivearea",
                        verbose_name="Associated Sensitivity Areas",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="unique Id",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date"
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, null=True, verbose_name="Remarks"
                    ),
                ),
                (
                    "last",
                    models.BooleanField(
                        default=True, verbose_name="Last record"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Equipements",
                        related_name="equipment",
                        related_query_name="operations",
                        to="cables.equipment",
                        verbose_name="Equipments",
                    ),
                ),
                (
                    "infrastructure",
                    models.ForeignKey(
                        help_text="Infrastructure attached with this Action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="cables.infrastructure",
                        verbose_name="Infrastructure attached with this Action",
                    ),
                ),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Media attached with this diagnosis",
                        related_name="operations_media",
                        related_query_name="operations",
                        to="media.media",
                        verbose_name="Media attached with this diagnosis",
                    ),
                ),
                (
                    "operation_type",
                    models.ForeignKey(
                        help_text="Type of operation",
                        limit_choices_to={"type__mnemonic": "operation_type"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_type",
                        to="sinp_nomenclatures.nomenclature",
                        verbose_name="Type of operation",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "infrastructure_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cables.infrastructure",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cables.infrastructure",),
        ),
        migrations.CreateModel(
            name="LineOperation",
            fields=[
                (
                    "operation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cables.operation",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
            bases=("cables.operation",),
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "infrastructure_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cables.infrastructure",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cables.infrastructure",),
        ),
        migrations.CreateModel(
            name="PointOperation",
            fields=[
                (
                    "operation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cables.operation",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
            ],
            options={
                "ordering": ["-date"],
                "abstract": False,
            },
            bases=("cables.operation",),
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="unique Id",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date"
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, null=True, verbose_name="Remarks"
                    ),
                ),
                (
                    "last",
                    models.BooleanField(
                        default=True, verbose_name="Last record"
                    ),
                ),
                (
                    "neutralized",
                    models.BooleanField(
                        default=False, verbose_name="Neutralized"
                    ),
                ),
                (
                    "isolation_advice",
                    models.BooleanField(
                        default=False, verbose_name="To be insulated"
                    ),
                ),
                (
                    "dissuasion_advice",
                    models.BooleanField(
                        default=False, verbose_name="Discourage"
                    ),
                ),
                (
                    "attraction_advice",
                    models.BooleanField(
                        default=False, verbose_name="Providing incentives"
                    ),
                ),
                (
                    "change_advice",
                    models.BooleanField(
                        default=False, verbose_name="Change arming"
                    ),
                ),
                (
                    "technical_proposal",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Technical proposal",
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        help_text="Pole condition",
                        limit_choices_to={
                            "type__mnemonic": "infrastr_condition"
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pole_condition",
                        to="sinp_nomenclatures.nomenclature",
                        verbose_name="Pole condition",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "infrastructure",
                    models.ForeignKey(
                        help_text="Infrastructure attached with this Action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosis",
                        to="cables.infrastructure",
                        verbose_name="Infrastructure attached with this Action",
                    ),
                ),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Media attached with this diagnosis",
                        related_name="diagnosis_media",
                        related_query_name="diagnosis",
                        to="media.media",
                        verbose_name="Media attached with this diagnosis",
                    ),
                ),
                (
                    "pole_attractivity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Attractivity level of risk",
                        limit_choices_to={"type__mnemonic": "risk_level"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pole_attractivity",
                        to="sinp_nomenclatures.nomenclature",
                        verbose_name="Attractivity level of risk",
                    ),
                ),
                (
                    "pole_dangerousness",
                    models.ForeignKey(
                        blank=True,
                        help_text="dangerousness level of risk",
                        limit_choices_to={"type__mnemonic": "risk_level"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pole_dangerousness",
                        to="sinp_nomenclatures.nomenclature",
                        verbose_name="dangerousness level of risk",
                    ),
                ),
                (
                    "pole_type",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Type of pole",
                        limit_choices_to={"type__mnemonic": "pole_type"},
                        related_name="diagnosis_pole_type",
                        to="sinp_nomenclatures.nomenclature",
                        verbose_name="Type of pole",
                    ),
                ),
                (
                    "sgmt_build_integr_risk",
                    models.ForeignKey(
                        blank=True,
                        help_text="Building integration level of risk",
                        limit_choices_to={"type__mnemonic": "risk_level"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segment_building_integration_risk",
                        to="sinp_nomenclatures.nomenclature",
                        verbose_name="Building integration level of risk",
                    ),
                ),
                (
                    "sgmt_moving_risk",
                    models.ForeignKey(
                        blank=True,
                        help_text="moving level of risk",
                        limit_choices_to={"type__mnemonic": "risk_level"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segment_moving_risk",
                        to="sinp_nomenclatures.nomenclature",
                        verbose_name="moving level of risk",
                    ),
                ),
                (
                    "sgmt_topo_integr_risk",
                    models.ForeignKey(
                        blank=True,
                        help_text="Topological level of risk",
                        limit_choices_to={"type__mnemonic": "risk_level"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segment_topological_integration_risk",
                        to="sinp_nomenclatures.nomenclature",
                        verbose_name="topological level of risk",
                    ),
                ),
                (
                    "sgmt_veget_integr_risk",
                    models.ForeignKey(
                        blank=True,
                        help_text="vegetation level of risk",
                        limit_choices_to={"type__mnemonic": "risk_level"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segment_vegetation_risk",
                        to="sinp_nomenclatures.nomenclature",
                        verbose_name="vegetation level of risk",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Diagnosis",
            },
        ),
    ]
