# Generated by Django 4.2.7 on 2024-02-22 08:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="unique Id",
            ),
        ),
    ]
