# Generated by Django 4.2.14 on 2024-07-31 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_name_alter_type_status"),
        ("cables", "0004_equipment_alter_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diagnosis",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="diagnosis",
            name="neutralized",
        ),
        migrations.AlterField(
            model_name="equipment",
            name="type",
            field=models.ForeignKey(
                help_text="Type of equipment",
                limit_choices_to={"type__mnemonic": "equipment_type"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_pole_eqmt_type",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Type of equipment",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="operation_type",
            field=models.ForeignKey(
                help_text="Type of operation",
                limit_choices_to={"type__code": "OP_TYPE"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operation_type",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Type of operation",
            ),
        ),
    ]
