# Generated by Django 4.2.14 on 2024-09-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo_area", "0002_alter_geoarea_geom"),
        (
            "cables",
            "0006_remove_operation_operation_type_alter_equipment_type",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infrastructure",
            name="geo_area",
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="areas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Associated Administrative and Natural Areas",
                related_name="%(class)s_areas",
                to="geo_area.geoarea",
                verbose_name="Associated Administrative and Natural Areas",
            ),
        ),
    ]
