# Generated by Django 4.2.14 on 2024-09-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sinp_nomenclatures", "0001_initial"),
        ("cables", "0007_remove_infrastructure_geo_area_infrastructure_areas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diagnosis",
            name="sgmt_veget_integr_risk",
        ),
        migrations.RemoveField(
            model_name="diagnosis",
            name="sgmt_build_integr_risk",
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="sgmt_landscape_integr_risk",
            field=models.ForeignKey(
                blank=True,
                help_text="Landscape level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_landscape_risk",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Landscape level of risk",
            ),
        ),
    ]
