# Generated by Django 4.2.16 on 2024-11-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "sinp_nomenclatures",
            "0004_alter_nomenclature_status_alter_source_name_and_more",
        ),
        ("cables", "0008_remove_diagnosis_sgmt_veget_integr_risk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="sgmt_landscape_integr_risk",
            field=models.ForeignKey(
                blank=True,
                help_text="Landscape level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_landscape_risk",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="landscape level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="sgmt_moving_risk",
            field=models.ForeignKey(
                blank=True,
                help_text="Moving level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_moving_risk",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="moving level of risk",
            ),
        ),
    ]
