# Generated by Django 4.2.16 on 2025-01-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cables", "0009_alter_diagnosis_sgmt_landscape_integr_risk_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diagnosis",
            old_name="pole_type",
            new_name="arming"
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="arming",
            field=models.ManyToManyField(
                blank=True,
                help_text="Armings",
                limit_choices_to={"type__mnemonic": "arming"},
                related_name="diagnosis_arming",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Armings",
            ),
        ),
    ]
