# Generated by Django 4.2.16 on 2025-02-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cables", "0010_remove_diagnosis_pole_type_diagnosis_arming"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="neutralization_level",
            field=models.CharField(
                choices=[("partial", "Partial"), ("full", "Full")],
                default="full",
                max_length=20,
            ),
        ),
    ]
