# Generated by Django 4.2.16 on 2025-07-17 08:05

from django.db import migrations, models
import django.db.models.deletion


def set_network_type(apps, schema_editor):
    Infrastructure = apps.get_model('cables', 'Infrastructure')
    Nomenclature = apps.get_model('sinp_nomenclatures', 'Nomenclature')
    htb_network_nomenclature = Nomenclature.objects.get(type__mnemonic='network_type',code='HTB')
    hta_network_nomenclature = Nomenclature.objects.get(type__mnemonic='network_type',code='HTA-BT')
    Infrastructure.objects.filter(owner__code='IO-RTE').update(network_type=htb_network_nomenclature)
    Infrastructure.objects.filter(owner__code='IO-ENEDIS').update(network_type=hta_network_nomenclature)


class Migration(migrations.Migration):
    dependencies = [
        ("cables", "0011_operation_neutralization_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructure",
            name="network_type",
            field=models.ForeignKey(
                help_text="Infrastructure network type",
                limit_choices_to={"type__mnemonic": "network_type"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_network_type",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Infrastructure network type",
            ),
        ),
        migrations.RunPython(set_network_type, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="infrastructure",
            name="network_type",
            field=models.ForeignKey(
                help_text="Infrastructure network type",
                limit_choices_to={"type__mnemonic": "network_type"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_network_type",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Infrastructure network type",
            ),
        ),
        migrations.RemoveField(
            model_name="infrastructure",
            name="owner",
        ),
    ]
