# Generated by Django 4.2.27 on 2026-01-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cables", "0012_remove_infrastructure_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="burial_advice",
            field=models.BooleanField(default=False, verbose_name="To bury"),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="visibility_advice",
            field=models.BooleanField(
                default=False, verbose_name="Make visible"
            ),
        ),
    ]
