# Generated by Django 4.2.16 on 2025-03-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0005_media_alter_uuid"),
        ("species", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="media.media",
                verbose_name="Photo",
            ),
        ),
    ]
