# Generated by Django 4.2.7 on 2024-02-22 08:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0004_media_gen_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
