# Generated by Django 4.2.16 on 2025-03-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0005_media_alter_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="label",
            field=models.CharField(
                blank=True, null=True, verbose_name="label"
            ),
        ),
    ]
