# Generated by Django 4.2.16 on 2025-03-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sinp_organisms",
            "0002_alter_organismmember_unique_together_and_more",
        ),
        ("users", "0003_user_avatar_alter_organism_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="organism",
        ),
        migrations.AddField(
            model_name="user",
            name="organisms",
            field=models.ManyToManyField(
                related_name="organisms",
                through="sinp_organisms.OrganismMember",
                to="sinp_organisms.organism",
                verbose_name="Organisms",
            ),
        ),
        migrations.DeleteModel(
            name="Organism",
        ),
    ]
