# Generated by Django 4.2.16 on 2025-03-11 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_organism_user_organisms_delete_organism"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    (
                        "change_active_status",
                        "Can change the active status for users in managed areas",
                    )
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
