# Generated by Django 4.2.16 on 2025-03-11 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="areas",
            field=models.ForeignKey(
                blank=True,
                help_text="The geographical area in which the user will be working? To validate registrations, user MUST also be in 'manage_registration' group)?",
                limit_choices_to={"type__mnemonic": "geographic_area"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="areas",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Geographical area of intervention",
            ),
        ),
    ]
