# Generated by Django 4.2.16 on 2025-03-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_token",
            field=models.CharField(
                blank=True,
                default="EJ41C87toOjiK8RDLJ43dMVzhkAY8gGfQvErorBc4CBl3iXpgf4LtIBEQn0rzrRC",
                max_length=250,
                null=True,
            ),
        ),
    ]
