# Generated by Django 4.2.16 on 2025-03-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_email_verified_user_registration_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="areas",
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_token",
            field=models.CharField(
                blank=True,
                default="V7vlGWJhb8Tp9CS3H74UY1kBffXRxXd1kXQAWhXGiPLzMdOcGkhF4mO8u7Rtvdwf",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="areas",
            field=models.ManyToManyField(
                help_text="The geographical area in which the user will be working? To validate registrations, user MUST also be in 'manage_registration' group)?",
                limit_choices_to={"type__mnemonic": "geographic_area"},
                related_name="areas",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Geographical area of intervention",
            ),
        ),
    ]
