# Generated by Django 4.2.16 on 2025-03-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0008_remove_user_areas_alter_user_registration_token_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_token",
            field=models.CharField(
                blank=True,
                default="S1wQf0zW5Dg7ZaljvkO0Nfoc0bHlWGqdtY0xT02FScwQj1UagjxBbLlVbw6SQo7f",
                max_length=250,
                null=True,
            ),
        ),
    ]
