# Generated by Django 4.2.16 on 2025-03-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_is_active_alter_user_registration_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="areas",
            field=models.ManyToManyField(
                help_text="The geographical area in which the user will be working? To validate registrations, user MUST also be in 'manage_registration' group)?",
                limit_choices_to={"type__mnemonic": "geographic_areas"},
                related_name="areas",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Geographical area of intervention",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_token",
            field=models.CharField(
                blank=True,
                default="sxPgB3WZhGYQJ7vxkk5elyy57Sjvk9PETv8e4kWqsdwOXVFd8F5wm1UMWHxBcXPi",
                max_length=250,
                null=True,
            ),
        ),
    ]
