# Generated by Django 4.2.16 on 2025-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_user_areas_alter_user_registration_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_token",
            field=models.CharField(
                blank=True,
                default="5CMkSSgpjtrz995AueGV41pLld3Gcw2TZtRR7X4e0lXIOp3FUbMrbYBj3UGR2NKX",
                max_length=250,
                null=True,
            ),
        ),
    ]
