# Generated by Django 4.2.27 on 2026-01-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_email_alter_user_registration_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="registration_token",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
